services:
  - type: web
    name: api_todo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com